project_id = "rxzubvqznmvvarmfsioe"

[functions.check-subscription]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = false

[functions.test-mapbox-token]
verify_jwt = false

[functions.generate-ai-route]
verify_jwt = true

[functions.generate-route]
verify_jwt = true

[functions.check-route-limit]
verify_jwt = false

[functions.record-route-generation]
verify_jwt = true

[functions.create-stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.customer-portal]
verify_jwt = true

[functions.send-auth-email]
verify_jwt = false
