// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxzubvqznmvvarmfsioe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4enVidnF6bm12dmFybWZzaW9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MjQ3OTgsImV4cCI6MjA3MTAwMDc5OH0.Y87Xww3ltLX79mDCxs0medXzy_xA1nQywU4rKWMJvM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});